### ISSUE TITLE
DOS-attack when connection fails

### ISSUE THREAD

**Issue by geon** [bdemirkir/node-modbus#1]
Client.prototype._onClose calls this._connect(). It will cause hundreds of (failed) connects per second when the address or port are wrong, or the network is down, or...

It would be better if the failed connect gave an error to the callback in Client.prototype.request.

**Comment by bdemirkir** [comment]
This code is (actually was) very experimental. I don't recommend to use it.

The attack is intentional. You're getting an error to your request actually (i didn't test it since i wrote it) but it will try to connect itself. That was my requirement at that moment.

Right now, i don't have any time to maintain this project. Feel free to fork it if you want.
